<?php
/*
 * to add a new employee
 */
$title = "Add an employee";
$this->headTitle($title);
?>
<div class="main-nav">
    <ul class="nav">
        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('category') ?>"><?php echo $this->translate('Category') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('employee') ?>"><?php echo $this->translate('Employee') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('message') ?>"><?php echo $this->translate('Messages ') ?></a></li>
        <li class="active"><a href=""><?php echo $this->translate('Attendance ') ?></a></li>
        <li class="logout"><a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">Logout</a></li>
        <li class="welcome-user">Hi Admin</li>
    </ul>
</div><!--/.nav-collapse -->
<div class="secondary-nav">
    <ul>
        <li class="active"><a href="<?php echo $this->url('employee', array('action'=>'add'));?>">Add new employee </a></li>
        <li class="active"><a href="<?php echo $this->url('employee', array('action'=>'search'));?>">Search employee</a></li>
        <li class="active"><a href="<?php echo $this->url('employee', array('action'=>'index'));?>">View all employees</a></li>
    </ul>
</div>
<div class="content">
    <h1><?php echo $this->escapeHtml ($title); ?></h1>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('employee' ,array('action' => 'add')));
    $form->prepare();

    //to have the form here
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>