<?php
/*
 * to search an employee
 */
$title = 'Search';
$this->headTitle($title);
?>
<div class="main-nav">
    <ul class="nav">
        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('category') ?>"><?php echo $this->translate('Category') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('employee') ?>"><?php echo $this->translate('Employee') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('message') ?>"><?php echo $this->translate('Messages ') ?></a></li>
        <li class="active"><a href=""><?php echo $this->translate('Attendance ') ?></a></li>
        <li class="logout"><a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">Logout</a></li>
        <li class="welcome-user">Hi Admin</li>
    </ul>
</div><!--/.nav-collapse -->
<div class="secondary-nav">
    <ul>
        <li class="active"><a href="<?php echo $this->url('employee', array('action'=>'add'));?>">Add new employee </a></li>
        <li class="active"><a href="<?php echo $this->url('employee', array('action'=>'search'));?>">Search employee</a></li>
        <li class="active"><a href="<?php echo $this->url('employee', array('action'=>'index'));?>">View all employees</a></li>
    </ul>
</div>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="cearch_form">
        <?php
        $url = $this->url('employee', array(
            'action' => 'search'
        ));

        ?>
        <form action="<?php echo $url; ?>" method="get">
            <label>Name</label><input type="text" name="search_name" />
            <!--  <label>Category</label><input type="text" name="search_category" /> -->
            <input type="submit" name="search_sub" value="Search" />
        </form>
    </div>
    <?php if( isset ($search_results)) { ?>
    <div class="search_results">
        <?php if(!empty ($search_results))
            { ?>
        <table class="table">
            <tr>
                <th>#</th>
                <th>Employee Name</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
        <?php $num = 1; 

                foreach ($search_results as $result) : ?>
            <tr>
                <td><?php echo $num; ?></td>
                <td><?php echo $this->escapeHtml($result->emp_name);?></td>
                <td>
                    <a href="<?php echo $this->url('employee',
                        array('action'=>'edit', 'id' => $result->emp_id));?>">Edit</a>
                </td>
                <td>
                    <a href="<?php echo $this->url('employee',
                        array('action'=>'delete', 'id' => $result->emp_id));?>">Delete</a>
                </td>
            </tr>
        <?php $num++; ?>
        <?php endforeach; ?>
        </table>
        <?php } else echo "<div>Sorry no results found</div>"; ?>
    </div>
    <?php } 

    ?>
</div>