<?php
$title = "Sent Items";
$this->headTitle($title);
?>
<div class="main-nav">
    <ul class="nav">
        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('category') ?>"><?php echo $this->translate('Category') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('employee') ?>"><?php echo $this->translate('Employee') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('message') ?>"><?php echo $this->translate('Messages ') ?></a></li>
        <li class="active"><a href=""><?php echo $this->translate('Attendance ') ?></a></li>
        <li class="logout"><a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">Logout</a></li>
        <li class="welcome-user">Hi Admin</li>
    </ul>
</div><!--/.nav-collapse -->
<div class="secondary-nav">
    <ul>
        <li class="active"><a href="<?php echo $this->url('message', array('action' => 'send')); ?>" >Personal Message</a></li>
        <li class="active"><a href="<?php echo $this->url('message', array('action' => 'sendToCategory')); ?>" >Category Message</a></li>
        <li class="active"><a href="<?php echo $this->url('message', array('action' => '')); ?>" >Inbox</a></li>
        <li class="active"><a href="<?php echo $this->url('message', array('action' => 'sentItems')); ?>" >Sent items</a></li>
    </ul>
</div>
<div class="content">
    <h1><?php echo $this->escapehtml($title); ?></h1>
    
    <?php
    foreach($sentItems as $sentItem)
    {
        echo "<div>";
        //echo $sentItem->mail_id;
        echo $sentItem->mail_subject;
        echo $sentItem->mail_body;
        echo "<br /></div>";
    }
   ?> 
</div>