<?php
//module/admin/view/admin/category/delete.phtml
$title = 'Delete category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    Are you sure that you want to delete category 
    '<?php echo $this->escapeHtml($category->category); ?>'?
</p>
<?php
$url = $this->url('category',array(
    'action' => 'delete',
    'id' => $this->id
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div> 
</form>