<?php
$title = 'Employee Category';
$this->headTitle($title);
?>
<div class="main-nav">
    <ul class="nav">
        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('category') ?>"><?php echo $this->translate('Category') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('employee') ?>"><?php echo $this->translate('Employee') ?></a></li>
        <li class="active"><a href="<?php echo $this->url('message') ?>"><?php echo $this->translate('Messages ') ?></a></li>
        <li class="active"><a href=""><?php echo $this->translate('Attendance ') ?></a></li>
        <li class="logout"><a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">Logout</a></li>
        <li class="welcome-user">Hi Admin</li>
    </ul>
</div><!--/.nav-collapse -->
<div class="secondary-nav">
    <ul>
        <li class="active"><a href="<?php echo $this->url('category',array('action'=>'add')); ?>" >Add new category</a></li>
        <li class="active"><a href="<?php echo $this->url('category',array('action'=>'index')); ?>" >View all categories</a></li>
    </ul>
</div>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
    <tr>
        <th>#</th>
        <th>Employee Category</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php $num = 1; ?>
    <?php foreach ($categories as $category) : ?>
    <tr>
        <td><?php echo $num; ?></td>
        <td><?php echo $this->escapeHtml($category->category);?></td>
        <td>
            <a href="<?php echo $this->url('category',
                array('action'=>'edit', 'id' => $category->id));?>">Edit</a>
        </td>
        <td>
            <a href="<?php echo $this->url('category',
                array('action'=>'delete', 'id' => $category->id));?>">Delete</a>
        </td>
    </tr>
    <?php $num++; ?>
    <?php endforeach; ?>
    </table>
</div>